services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    restart: unless-stopped
    ports:
      - "8080:8080"      # REST
      - "50051:50051"    # gRPC  ✅
    environment:
      CLUSTER_HOSTNAME: "node1"
      DEFAULT_VECTORIZER_MODULE: "none"
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "bm25"
      DISABLE_TELEMETRY: "true"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    networks:
      - weavelens_net

networks:
  weavelens_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
